"""add users and organization slugs

Revision ID: 036aad5be6cf
Revises: 7ba78bf334c9
Create Date: 2026-09-10 13:00:46.591715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '036aad5be6cf'
down_revision: Union[str, Sequence[str], None] = '7ba78bf334c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email', name='uq_users_organization_email')
    )
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.add_column('organizations', sa.Column('slug', sa.String(length=100), nullable=True))

    connection = op.get_bind()

    connection.execute(
        sa.text(
            '''
            UPDATE organizations
            SET slug = lower(
                regexp_replace(
                    trim(both '-' from regexp_replace(name, '[^a-zA-Z0-9]+', '-', 'g')),
                    '-+',
                    '-',
                    'g'
                )
            ) || '-' || left(id::text, 8)
            WHERE slug IS NULL
            '''
        )
    )

    op.alter_column(
        'organizations',
        'slug',
        existing_type=sa.String(length=100),
        nullable=False,
    )

    op.create_unique_constraint(
        'uq_organizations_slug',
        'organizations',
        ['slug'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_organizations_slug', 'organizations', type_='unique')
    op.drop_column('organizations', 'slug')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
