"""add autonomous research workflow

Revision ID: ed4c5a8f97b4
Revises: 036aad5be6cf
Create Date: 2026-09-10 15:03:13.553453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed4c5a8f97b4'
down_revision: Union[str, Sequence[str], None] = '036aad5be6cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('procurement_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['procurement_id'], ['procurements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_runs_procurement_id'), 'research_runs', ['procurement_id'], unique=False)
    op.create_table('supplier_offers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('procurement_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('availability', sa.String(length=255), nullable=True),
    sa.Column('warranty', sa.String(length=500), nullable=True),
    sa.Column('specifications', sa.JSON(), nullable=True),
    sa.Column('matching_result', sa.JSON(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['procurement_id'], ['procurements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_offers_procurement_id'), 'supplier_offers', ['procurement_id'], unique=False)
    op.create_table('research_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('research_run_id', sa.Uuid(), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('external_job_id', sa.String(length=255), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_tasks_external_job_id'), 'research_tasks', ['external_job_id'], unique=False)
    op.create_index(op.f('ix_research_tasks_research_run_id'), 'research_tasks', ['research_run_id'], unique=False)
    op.create_table('research_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('research_run_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_sources_research_run_id'), 'research_sources', ['research_run_id'], unique=False)
    op.create_index(op.f('ix_research_sources_task_id'), 'research_sources', ['task_id'], unique=False)
    op.create_table('offer_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('offer_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['supplier_offers.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['research_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_evidence_offer_id'), 'offer_evidence', ['offer_id'], unique=False)
    op.create_index(op.f('ix_offer_evidence_source_id'), 'offer_evidence', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offer_evidence_source_id'), table_name='offer_evidence')
    op.drop_index(op.f('ix_offer_evidence_offer_id'), table_name='offer_evidence')
    op.drop_table('offer_evidence')
    op.drop_index(op.f('ix_research_sources_task_id'), table_name='research_sources')
    op.drop_index(op.f('ix_research_sources_research_run_id'), table_name='research_sources')
    op.drop_table('research_sources')
    op.drop_index(op.f('ix_research_tasks_research_run_id'), table_name='research_tasks')
    op.drop_index(op.f('ix_research_tasks_external_job_id'), table_name='research_tasks')
    op.drop_table('research_tasks')
    op.drop_index(op.f('ix_supplier_offers_procurement_id'), table_name='supplier_offers')
    op.drop_table('supplier_offers')
    op.drop_index(op.f('ix_research_runs_procurement_id'), table_name='research_runs')
    op.drop_table('research_runs')
    # ### end Alembic commands ###
